### PR TITLE
my test task

### PR DESCRIPTION
**Pull request by PhazZzyo**
We had a meeting yesterday. Here is my test task, you asked for.

### CODE REVIEW

**Comment by vovkanaz** [comment]
Where are kubernetes playbooks?

**Comment by hex-344505** [comment]
POSTGRES_USER: "user"
          POSTGRES_PASSWORD: "pass"
Useless, backend didnt use it

Rails will not start cause 2 important files does not exist.

Just IMHO

**Comment by vovkanaz** [comment]
Wish you good luck

**Comment by PhazZzyo** [comment]
Closed

**Pull request closed without merging**
