### PR TITLE
Volume added in docker-compose.yaml

### PR DESCRIPTION
**Pull request by hex-344505**

### CODE REVIEW

**Comment by vovkanaz** [comment]
Can you get access to your cluster from the internet? I'm not sure about Service status: loadbalancer: {}
 and where you cluster have been created Minikube, AWS?

**Comment by vovkanaz** [comment]
Try to deploy kubernetes cluster on AWS, DigitalOcean, Google Cloud as you wish(this is not important for now), but we want to see clear kubernetes instead of Minikube, and your Frontend should be available from the www

**Comment by hex-344505** [comment]
http://104.155.93.102/ here deployed
have to use this command
kubectl expose deploy hex-nginx --type=LoadBalancer --port 80 --target-port 80

**Comment by hex-344505** [comment]
I cant use this construction because of dynamic addresses
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.0.10

**Comment by vovkanaz** [comment]
Ok, got it, what about rails web interface?

**Comment by hex-344505** [comment]
http://35.240.8.71:3000/
to make it happen
kubectl expose deploy hex-back --name=back-web --type=LoadBalancer --port 3000 --target-port=3000

**Pull request closed without merging**
